import { useState, useEffect } from "react"; // Step 1: Import useEffect
// import { nanoid } from 'nanoid'; // Step 1: nanoid import - using simple counter for now
import jsPDF from "jspdf";
import html2canvas from "html2canvas";
import "./App.css";

// Step 1: Import Block Components
import PersonalInfoBlock from './components/blocks/PersonalInfoBlock';
import AcademicQualificationsBlock from './components/blocks/AcademicQualificationsBlock';
import ProfessionalQualificationsBlock from './components/blocks/ProfessionalQualificationsBlock';
import WorkExperienceBlock from './components/blocks/WorkExperienceBlock';
import LanguagesBlock from './components/blocks/LanguagesBlock';
import HobbiesInterestsBlock from './components/blocks/HobbiesInterestsBlock';

// Import Form Components (Step 4)
import PersonalInfoForm from './components/forms/PersonalInfoForm';
import AcademicQualificationsForm from './components/forms/AcademicQualificationsForm';
import WorkExperienceForm from './components/forms/WorkExperienceForm';
import ProfessionalQualificationsForm from './components/forms/ProfessionalQualificationsForm';
import LanguagesForm from './components/forms/LanguagesForm';
import HobbiesInterestsForm from './components/forms/HobbiesInterestsForm';

// Step 3: Initialize nextId and generateId
let nextId = 0;
const generateId = () => `block-${nextId++}`;

function App() {
  // Step 2: Remove Old cvData State
  // const [cvData, setCvData] = useState({
  //   name: "",
  //   email: "",
  //   education: "",
  //   experience: "",
  //   skills: "",
  // });

  // Step 1: Define defaultBlockContent (should be outside App or memoized if inside, but for this structure, it's fine here)
  const defaultBlockContent = {
    personalInfo: { name: 'New Name', email: '', phone: '', linkedIn: '', summary: '' },
    education: { degree: 'New Degree', institution: '', year: '', grades: '' },
    experience: { jobTitle: 'New Job', employer: '', duration: '', responsibilities: '' },
    professionalQualifications: { certification: 'New Certification', specialization: '', trainingBody: '', year: '' },
    languages: { language: 'New Language', fluency: 'Basic' },
    hobbiesInterests: { text: 'New Hobby' },
  };

  // Default initial blocks (if local storage is empty or invalid) - defined before useState
  const initialBlocksData = [
    // IDs will be generated by the useState initializer if this data is used
    { type: 'personalInfo', content: { ...defaultBlockContent.personalInfo, name: 'Your Name', email: 'your.email@example.com', summary: 'A brief summary about you.'} },
    { type: 'education', content: { ...defaultBlockContent.education, degree: 'B.S. in Computer Science', institution: 'University of Example', year: '2020', grades: 'GPA: 3.8/4.0' } },
    { type: 'experience', content: { ...defaultBlockContent.experience, jobTitle: 'Software Developer', employer: 'Tech Company Inc.', duration: 'Jan 2021 - Present', responsibilities: 'Developed and maintained web applications.' } },
  ];

  // Step 2: Load from Local Storage on Mount (within useState initializer)
  const [blocks, setBlocks] = useState(() => {
    try {
      const storedBlocks = localStorage.getItem('cvBuilderBlocks');
      if (storedBlocks) {
        const parsedBlocks = JSON.parse(storedBlocks);
        if (Array.isArray(parsedBlocks) && parsedBlocks.length > 0) {
          let maxIdNum = -1;
          parsedBlocks.forEach(block => {
            if (block.id) { // Ensure block.id exists
              const idNumParts = block.id.split('-');
              if (idNumParts.length > 1) {
                const idNum = parseInt(idNumParts[1], 10);
                if (!isNaN(idNum) && idNum > maxIdNum) {
                    maxIdNum = idNum;
                }
              }
            }
          });
          nextId = maxIdNum + 1; // Update module-level nextId
          return parsedBlocks;
        }
      }
    } catch (error) {
      console.error("Error loading blocks from local storage:", error);
    }
    // Fallback to initialBlocksData if nothing in localStorage or if it's invalid
    nextId = 0; // Reset for initialBlocksData
    const blocksWithIds = initialBlocksData.map(block => ({...block, id: generateId()}));
    // nextId is already updated by generateId calls
    return blocksWithIds;
  });

  const [selectedTemplate, setSelectedTemplate] = useState("modern");

  // Step 3: Save to Local Storage on blocks Change
  useEffect(() => {
    try {
      localStorage.setItem('cvBuilderBlocks', JSON.stringify(blocks));
    } catch (error) {
      console.error("Error saving blocks to local storage:", error);
    }
  }, [blocks]);

  // Step 2: Create Block Type to Component Map
  const blockComponentMap = {
    personalInfo: PersonalInfoBlock,
    education: AcademicQualificationsBlock, // Map 'education' type to AcademicQualificationsBlock
    experience: WorkExperienceBlock,     // Map 'experience' type to WorkExperienceBlock
    professionalQualifications: ProfessionalQualificationsBlock,
    languages: LanguagesBlock,
    hobbiesInterests: HobbiesInterestsBlock,
  };

  // Step 4: Create blockFormMap
  const blockFormMap = {
    personalInfo: PersonalInfoForm,
    education: AcademicQualificationsForm,
    experience: WorkExperienceForm,
    professionalQualifications: ProfessionalQualificationsForm,
    languages: LanguagesForm,
    hobbiesInterests: HobbiesInterestsForm,
  };

  // Step 2: handleBlockContentChange in App.jsx
  const handleBlockContentChange = (blockId, fieldName, value) => {
    setBlocks(prevBlocks =>
      prevBlocks.map(block =>
        block.id === blockId
          ? { ...block, content: { ...block.content, [fieldName]: value } }
          : block
      )
    );
  };

  // Step 2: Implement addBlock function
  const addBlock = (type) => {
    if (!defaultBlockContent[type]) {
      console.error(`Unknown block type: ${type}`);
      return;
    }
    const newBlock = {
      id: generateId(), // Assumes generateId() is defined in App.jsx
      type: type,
      content: { ...defaultBlockContent[type] }, // Create a copy of default content
    };
    setBlocks(prevBlocks => [...prevBlocks, newBlock]);
  };

  // Step 3: Implement removeBlock function
  const removeBlock = (id) => {
    setBlocks(prevBlocks => prevBlocks.filter(block => block.id !== id));
  };

  // Step 1: Implement moveBlockUp and moveBlockDown functions
  const moveBlockUp = (blockId) => {
    setBlocks(prevBlocks => {
      const index = prevBlocks.findIndex(b => b.id === blockId);
      // Ensure block is found and is not the first non-personalInfo block
      const firstOrderableIndex = prevBlocks.findIndex(b => b.type !== 'personalInfo');
      if (index > 0 && index > firstOrderableIndex) {
        const newBlocks = [...prevBlocks];
        [newBlocks[index - 1], newBlocks[index]] = [newBlocks[index], newBlocks[index - 1]];
        return newBlocks;
      }
      return prevBlocks;
    });
  };

  const moveBlockDown = (blockId) => {
    setBlocks(prevBlocks => {
      const index = prevBlocks.findIndex(b => b.id === blockId);
      if (index !== -1 && index < prevBlocks.length - 1 && prevBlocks[index].type !== 'personalInfo') {
        const newBlocks = [...prevBlocks];
        [newBlocks[index + 1], newBlocks[index]] = [newBlocks[index], newBlocks[index + 1]];
        return newBlocks;
      }
      return prevBlocks;
    });
  };

  const templates = ["modern", "classic"];

  const downloadPDF = () => {
    const previewElement = document.getElementById("cv-preview");
    if (!previewElement) {
      console.error("CV preview element not found!");
      alert("Error: CV preview element not found. Cannot download PDF.");
      return;
    }

    // Optional: Add a loading indicator here if PDF generation is slow
    // E.g., set a state like `setIsGeneratingPdf(true)`

    html2canvas(previewElement, {
      scale: 2,
      logging: false, // Keep false unless debugging
      useCORS: true, // Good to have if images from URLs might be used
      onclone: (documentClone) => {
          // Modify the cloned document before capture
          const clonedPreview = documentClone.getElementById("cv-preview");
          if (clonedPreview) {
              clonedPreview.style.boxShadow = 'none'; // Remove box-shadow for cleaner PDF
              // Potentially hide .block-controls if they are part of the capture
              const blockControls = clonedPreview.querySelectorAll('.block-controls');
              blockControls.forEach(controls => controls.style.display = 'none');
          }
      }
    }).then((canvas) => {
      const imgData = canvas.toDataURL("image/png");
      const pdf = new jsPDF("p", "mm", "a4");
      const pdfWidth = pdf.internal.pageSize.getWidth();
      const pdfHeight = pdf.internal.pageSize.getHeight();

      const canvasWidth = canvas.width;
      const canvasHeight = canvas.height;

      // Scale image to fit A4, maintaining aspect ratio
      let ratio = Math.min(pdfWidth / canvasWidth, pdfHeight / canvasHeight);
      let imgWidth = canvasWidth * ratio;
      let imgHeight = canvasHeight * ratio;

      // Center the image on the PDF page
      const xOffset = (pdfWidth - imgWidth) / 2;
      const yOffset = (pdfHeight - imgHeight) / 2;

      pdf.addImage(imgData, "PNG", xOffset, yOffset, imgWidth, imgHeight);
      pdf.save("cv.pdf");
    }).catch(error => {
      console.error("Error generating PDF:", error);
      alert("An error occurred while generating the PDF. Please try again.");
    }).finally(() => {
      // Optional: Remove loading indicator here
      // E.g., setIsGeneratingPdf(false)
    });
  };

  return (
    <div className="App">
      <h1>CV Builder</h1>
      <div className="cv-container">
        <section className="form-section">
          <h2>Enter Your Details</h2>
          {/* Step 4: Add UI for Adding Blocks */}
          <div className="add-block-section">
            <select id="blockTypeSelector" defaultValue="education">
              {/* Filter out personalInfo as it's typically unique and present by default */}
              {Object.keys(defaultBlockContent).filter(type => type !== 'personalInfo').map(type => (
                <option key={type} value={type}>
                  {type.charAt(0).toUpperCase() + type.slice(1).replace(/([A-Z])/g, ' $1')} {/* Basic formatting for display */}
                </option>
              ))}
            </select>
            <button
              onClick={() => {
                const selector = document.getElementById('blockTypeSelector');
                addBlock(selector.value);
              }}
            >
              Add Section
            </button>
          </div>

          {/* Step 5 & 6: Render Forms in App.jsx's Form Section & pass removeBlock */}
          {blocks.map(block => {
            const FormComponent = blockFormMap[block.type];
            if (!FormComponent) {
              // Fallback for blocks that might not have a dedicated form yet
              return <p key={`form-${block.id}`}>No edit form for {block.type}</p>;
            }
            return (
              <FormComponent
                key={`form-${block.id}`}
                blockId={block.id}
                content={block.content}
                onContentChange={handleBlockContentChange}
                // Conditionally pass onRemoveBlock (Step 6)
                {...(block.type !== 'personalInfo' && { onRemoveBlock: removeBlock })}
              />
            );
          })}
          {/*
          <form>
            <label>
              Name:
              <input
                type="text"
                name="name"
                value={cvData.name}
                onChange={handleChange}
              />
            </label>
            <label>
              Email:
              <input
                type="email"
                name="email"
                value={cvData.email}
                onChange={handleChange}
              />
            </label>
            <label>
              Education:
              <textarea
                name="education"
                value={cvData.education}
                onChange={handleChange}
              />
            </label>
            <label>
              Experience:
              <textarea
                name="experience"
                value={cvData.experience}
                onChange={handleChange}
              />
            </label>
            <label>
              Skills:
              <textarea
                name="skills"
                value={cvData.skills}
                onChange={handleChange}
              />
            </label>
          </form>
          */}
        </section>
        <section className="preview-section">
          <h2>Preview</h2>
          <div className="template-selector">
            <label>Select Template: </label>
            {templates.map((template) => (
              <button
                key={template}
                onClick={() => setSelectedTemplate(template)}
                className={selectedTemplate === template ? "active" : ""}
              >
                {template.charAt(0).toUpperCase() + template.slice(1)}
              </button>
            ))}
          </div>
          <div id="cv-preview" className={`cv-preview ${selectedTemplate}`}>
            {/* Step 2: Pass reordering props from App.jsx to block components */}
            {blocks.map((block, index) => { // Make sure to get index
              const BlockComponent = blockComponentMap[block.type];
              if (!BlockComponent) {
                return <p key={block.id}>Unsupported block type: {block.type}</p>;
              }
              // Find the actual index of the first non-personalInfo block for "isEffectivelyFirstNonPersonalInfo" logic
              const firstOrderableBlockIndex = blocks.findIndex(b => b.type !== 'personalInfo');
              // A block is considered the "first orderable" if it's the first block of a type other than 'personalInfo'
              const isEffectivelyFirstOrderable = index === firstOrderableBlockIndex;

              const isLast = index === blocks.length - 1;

              return (
                <BlockComponent
                  key={block.id}
                  blockId={block.id}
                  content={block.content}
                  template={selectedTemplate}
                  onContentChange={handleBlockContentChange}
                  // Only allow moving if it's not the 'personalInfo' block
                  onMoveBlockUp={block.type !== 'personalInfo' && !isEffectivelyFirstOrderable ? moveBlockUp : null}
                  onMoveBlockDown={block.type !== 'personalInfo' && !isLast ? moveBlockDown : null}
                  // For disabling buttons inside the component
                  isFirstOrderable={block.type === 'personalInfo' || isEffectivelyFirstOrderable}
                  isLastOrderable={block.type === 'personalInfo' || isLast}
                />
              );
            })}
            {/*
            <h3>{cvData.name || "Your Name"}</h3>
            <p>{cvData.email || "Your Email"}</p>
            <h4>Education</h4>
            <p>{cvData.education || "Your Education"}</p>
            <h4>Experience</h4>
            <p>{cvData.experience || "Your Experience"}</p>
            <h4>Skills</h4>
            <p>{cvData.skills || "Your Skills"}</p>
            */}
          </div>
          <button className="download-btn" onClick={downloadPDF}>
            Download PDF
          </button>
        </section>
      </div>
    </div>
  );
}

export default App;